name: Deploy PHP Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Build code
        run: npm run build
      - name: Test code
        run: vendor/bin/phpunit
  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

